### ISSUE TITLE
Audio patches don't work in 12.2

### ISSUE THREAD

**Issue by applesjgtl** [syscl/XPS9350-macOS#11]
Graphics glitches and screen-off at bootup are actually fixed with update but audio doesn't work (no input/output devices). Happy to provide any needed logs or testing. I'm wondering if perhaps instead of manually patching if it would be worth looking into using AppleALC now that it has Skylake support. Perhaps this would get headphone jack working? https://github.com/toleda/audio_RealtekALC

**Comment by syscl** [comment]
Please provide at least your specification, otherwise no one can help

syscl

**Comment by applesjgtl** [comment]
Pretty sure there’s only one Intel/ALC audio card configuration available in various models of early 2016 XPS 13 9350. Am I mistaken?

On Mon, Dec 12, 2016 at 6:29 PM, Zhou Yating <notifications@github.com> wrote:
Please provide at least your specification, otherwise no one can help

syscl

**Comment by syscl** [comment]
I mean your laptop specification, e.g. i7-6500, QHD+, touchscreen, ...

syscl

**Comment by applesjgtl** [comment]
QHD+, touchscreen, i5-6200U, 8GB, 256GB

**Comment by zeusk** [comment]
I haven't tried the update but last week (when DSDT/SSDT weren't patched due to compile failure) - I didn't have audio working either. I will test the latest repo and report back tomorrow.

QHD+ (Touch disabled in UEFI), i7-6560U, 16GB, 512GB PM951

**Comment by gctseng** [comment]
I just ran the updated Deploy.sh earlier tonight and can report audio is not working. Haven't had a chance to do any further testing.  Let me know if you need anything else.

QHD+ (touchscreen enabled), i7-6560U, 16GB, 512GB NVMe THNSN5512GPUK NV, BIOS 1.4.10

**Comment by syscl** [comment]
@applesjgtl @zeusk @gctseng don't worry, I am still fixing those issues(not big issues) but give me time ok? 

To make you all ensure that XPS 13(SKL) works like a charm, see this
![img_8386](https://cloud.githubusercontent.com/assets/11594858/21130343/5c572736-c0cd-11e6-80c3-8d29368b630a.JPG)

The bugs you post are all I have foreseen, I know how to fix all of them, so please let me fix more important bugs(e.g. disk lose mount sometimes during startup, BrcmPatchRAM2 sometimes sucks booting, model identify...) first.

If you want to help, please provide as much as detailed information, e.g. make [ioreg](https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/) and something like that. Thank you!

syscl

**Comment by gctseng** [comment]
See enclosed.  I tried opening the file and it opened in ioreg, so I know it saved correctly.

[MacXPS.ioreg.zip](https://github.com/syscl/XPS9350-macOS/files/649831/MacXPS.ioreg.zip)

Thank you for what you're doing.  You're saving me a lot of time and luckily I have another Macbook I can still use, but I'm hoping to get rid of it as soon as possible and use the XPS as my daily driver before I leave on a trip on 12/20 (I don't want to have to carry 2 computers :) )

In "actual" use (i.e., when the laptop is stable), I hardly ever shutdown my computer. So, maybe in the order of importance (just my opinion, of course):
1. Basic keyboard and trackpad: Seems to be working fine, with two finger scrolling working, although the trackpad is not recognized as being a trackpad (e.g., Trackpad in control panel does not show anything). Can be solved later.
2. Sleep/Wake: Needs to be "perfect" because if this works then I won't care if I have to try and reboot a couple of times (again, rebooting for me occurs once every few weeks). I need to be able to open and close the lid and forget about it.  I haven't used the computer much yet.
3. Display: Seems to work fine with only glitching at startup.  However, brightness control option is not available.
4. AppleID: App Store, iTunes, and iCloud works. Haven't been able to test Messaging (no Bluetooth so I don't think handoff works-waiting on DW1830) or Facetime yet.
5. No sound, of course.

Keep up the good work.

**Comment by applesjgtl** [comment]
I'll upload my ioreg in 5-10 minutes. Thanks for all the hard work! This GitHub has made my life 1000x easier. This is the future of hackintoshing - we should distribute all custom repos this way :)


On Mon, Dec 12, 2016 at 10:49pm, Zhou Yating < notifications@github.com [notifications@github.com] > wrote:
@applesjgtl [https://github.com/applesjgtl] @zeusk [https://github.com/zeusk] @gctseng [https://github.com/gctseng] don't worry, I am still fixing those issues(not big issues) but give me time ok?

To make you all ensure that XPS 13(SKL) works like a charm, see this
[https://cloud.githubusercontent.com/assets/11594858/21130343/5c572736-c0cd-11e6-80c3-8d29368b630a.JPG]

The bugs you post are all I have foreseen, I know how to fix all of them, so please let me fix more important bugs(e.g. disk lose mount sometimes during startup, BrcmPatchRAM2 sometimes sucks booting, model identify...) first.

If you want to help, please provide as much as detailed information, e.g. make ioreg [https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/] and something like that. Thank you!

syscl

**Comment by applesjgtl** [comment]
[Dolores.zip](https://github.com/syscl/XPS9350-macOS/files/650281/Dolores.zip)
ioreg attached

**Comment by applesjgtl** [comment]
@gctseng supposedly the official VoodooPS2 driver already solved the issue. https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller

**Comment by syscl** [comment]
@gctseng Brightness slider? Or you need to use the latest deploy.sh to inject it. Do a clean build(under XPS9350-macOS/) by
```sh
tools/rebuild
./deploy.sh
```

I will fix more bugs, so don't worry, good things will come!

syscl

**Comment by syscl** [comment]
@applesjgtl yes, voodoops2 works stable with our touchpad, you can switch too it, I will later add an option for users to choose which controller you prefer to use. But as a fan of AppleSmartTouchPad(with multi finger function, 2f tap, 3f lookup dictionary in my version, 4f, 5f ...), I have to wait for EMlyDinEsH to fix AppleSmartTouchPad. Actually, fix of the driver has almost done, he contacted me and we will discuss about the driver this weekend. Thus, good things will happen soon.

syscl

**Comment by syscl** [comment]
@applesjgtl @zeusk @gctseng try the latest deploy.sh and config.plist to see if the audio can work or not

syscl

**Comment by x4080** [comment]
My audio was work just fine, I manually patch new changes with your instruction so not patching all at once

**Comment by x4080** [comment]
Apple smart touch pad works better I agree

**Comment by syscl** [comment]
@x4080 could you try the deploy.sh to see if the patch work, I want some feedbacks about my audio patches. Thanks.

syscl

**Comment by gctseng** [comment]
What's the difference between ./tools/rebuild and ./deploy?
I've ran ./tools/cleanup already so just need to know what to run next.  Also, I don't need to copy anything over to the EFI partition, right?

**Comment by syscl** [comment]
@gctseng rebuild just clean up all the previous acpi tables save in XPS9350-macOS to prevent some potential compile issue(just in case)

Yes, deploy.sh will do almost all of the patch. What about the latest deploy.sh and config.plist, is audio work now? I want to confirm...

Thanks,
syscl

**Comment by gctseng** [comment]
@syscl Okay. I'm running deploy.sh now and will report back in a few minutes.

**Comment by gctseng** [comment]
@syscl Haven't rebooted yet because I wanted to know what to do. I ran deploy and received this error:

`[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[FAILED]  Generate C-States and P-State for Intel i7-6560U .
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
[  OK  ]  Clean dynamic SSDTs.`

Rest of script ran fine.  Can I reboot with that error for power management?

**Comment by syscl** [comment]
OK, that's fine, because I have copy that ssdt yet. 

syscl

**Comment by gctseng** [comment]
@syscl Sorry, one more question. I don't have to copy the config.plist over to the EFI partition, right?

**Comment by syscl** [comment]
@gctseng backup your original config.plist to config-bak.plist(once you boot failed, you can select the backup config.plist under Clover GUI).

You have to copy the latest config.plist to the EFI/Clover

syscl

**Comment by gctseng** [comment]
@syscl Update:
**Audio**: No joy. The system doesn't see any devices still.
**LCD Brightness**: The brightness slider in the Display system preferences is there now! :)
**Brightness keys**: No joy. I also noticed that I have to press FN key otherwise the keyboard defaults to F-keys.
**Sleep**:  The system seems to go to sleep when I close the lid.
**Resume**:  Reboots when I open the lid (I only tested it once because I wanted to give you an update ASAP). I'll test stuff again and update.
**Shutdown**: I didn't mention this before, but I believe every time I try to shut down, the system will shut down and automatically reboot.

**Comment by applesjgtl** [comment]
I'm pretty sure there's a halt restart KEXT that fixes this.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.26&pv=7.1&source=email_footer_2] On Tue, Dec 13, 2016 at 10:29pm, George Tseng < notifications@github.com [notifications@github.com] > wrote:
@syscl [https://github.com/syscl] Update:
Audio : No joy. The system doesn't see any devices still.
LCD Brightness : The brightness slider in the Display system preferences is there now! :)
Brightness keys : No joy. I also noticed that I have to press FN key otherwise the keyboard defaults to F-keys.
Sleep : The system seems to go to sleep when I close the lid.
Resume : Reboots when I open the lid (I only tested it once because I wanted to give you an update ASAP). I'll test stuff again and update.
Shutdown : I didn't mention this before, but I believe every time I try to shut down, the system will shut down and automatically reboot.

**Comment by syscl** [comment]
@gctseng thks for the feedback, I have to refine it...

syscl

**Comment by syscl** [comment]
@gctseng try the latest config.plist, I figure out that it's the clover's issue that inject id = 0 for our devices which is mean do nothing in clover before.

syscl

**Comment by gctseng** [comment]
@syscl What issue does this fix/address? Will try it this morning.
@applesjgtl Thanks, I'll look for that kext later today.

**Comment by gctseng** [comment]
@syscl Used the lastest config.plist. Updating test results to below item(s) only:

**Audio**: Speakers and microphone works!(n1)  However, I hear significant buzzing noise over sound/music on the headphone jack when I plug in regular headphones, and just buzzing noise when I plug in Apple headphones (with the microphone).

(n1) It did take a couple of reboots for the microphone to show up even though the speakers showed up after the first reboot.  Actually, I believe the second "reboot" was a "shutdown", which made the difference--maybe it forced Clover to reinitialize?

**Comment by syscl** [comment]
@gctseng hold on a second, I now upload the fix 

syscl

**Comment by syscl** [comment]
@gctseng try the latest deploy.sh, I fixed a bug that cause by AppleHDA
1. High CPU % credit syscl

syscl

**Comment by gctseng** [comment]
@syscl Trying it now. give me 10 minutes.

**Comment by gctseng** [comment]
@syscl Update XPS9350 Run: 2016-12-14 10:04
- High CPU use gone.
- Headphone has distorted playback.
- Apple headset still doesn't work (I have to investigate whether it works or not in general).

Notes:
- You probably want to put the "cat ...config.plist" command after you mount the EFI directory.
- Since last night (2 commits ago?), booting was a lot faster.
- I'm not sure I have enough data, but booting in verbose mode seems to be more reliable (I've had at least 2-out-of-3 hangs when booting in regular mode, and only 1/10 hangs in verbose mode; probably a Clover issue?)

**Comment by syscl** [comment]
@gctseng Booting faster is right, since I fixed the sensorhub acpi.

Apple headset will work, since I am using Apple HP listening music now. I have to tune CodecCommander for this project. Give me 10mins

syscl

**Comment by gctseng** [comment]
@syscl Update XPS9350 Run (commit  6595d0b): 2016-12-14 12:59
- Headphones output without distortion!
- Apple headphones works for output, but not microphone (i.e., sound input remains on internal microphone).  Let me know if this is expected behavior, if it is, then all audio issues I can test are resolved (I don't have HDMI/DP adapter).

Notes:
- Deploy.sh didn’t ask for password for installing audio.

**Comment by gctseng** [comment]
@syscl Just an FYI regarding Apple Headphones (at least why the mic doesn't work):

[http://en.community.dell.com/support-forums/laptop/f/3517/t/19658042](url)
[http://en.community.dell.com/support-forums/laptop/f/3517/t/19632353?pi41097=3](url)

Thanks for getting the audio up!
