### ISSUE TITLE
External Display (USB-C to DisplayPort) not Working

### ISSUE THREAD

**Issue by riptidewave93** [syscl/XPS9350-macOS#46]
Hello, first off I want so say great work on this repo!

Currently I am unable to get external displays to work with my XPS 13. My laptop model specs are:
Core i7 6560U
Intel Iris 540 Graphics
8GB DDR3
HighDPI Display (3,200 x 1,800)

The issue is that OSX detects the display, and properly shows supported resolutions, but the external display never detects a signal.

<img width="1600" alt="screen shot 2017-02-05 at 2 33 20 pm" src="https://cloud.githubusercontent.com/assets/4700774/22641371/13a56488-ec1c-11e6-85c7-1bbb79d7ac7e.png">
![img_20170205_143340](https://cloud.githubusercontent.com/assets/4700774/22641398/394847aa-ec1c-11e6-8181-8ca99ad075fe.jpg)

The adapter I am trying to use can be found at https://www.amazon.com/AllSmartLife-DisplayPort-Aluminium-resolution-ChromeBook/dp/B017TZTMBG, and works on Linux (4.10 kernel) and Windows 10.

Please let me know what information I can provide to try and help get this resolved.

**Comment by R1MnTnA** [comment]
Please also see issue #33

**Comment by R1MnTnA** [comment]
@riptidewave93 Did issue #33 help to resolve this issue? If so please close.

**Comment by riptidewave93** [comment]
@R1MnTnA Sadly nothing in https://github.com/syscl/XPS9350-macOS/issues/33 helps. This issue occurs when the device is booted with the adapter, or when it's hot-plugged. Either way, it fails to display on my display.

**Comment by R1MnTnA** [comment]
You may want to try a different model then. Some of the reviews on Amazon say it doesn't work on people's MacBooks. Even though it says it says it in the title. I ordered this one- TechOrbits USB 3.1 Type C (USB-C & Thunderbolt 3 Port Compatible) to HDMI Adapter 4K Resolution USB-C to HDMI Support for MacBook Chromebook Pixel and https://www.amazon.com/dp/B01G2OB1AK/ref=cm_sw_r_cp_apip_o444MR97wRFIl and video works great, but still can't get audio to work through HDMI to TV on Mac, works fine on Windows though. Not sure if the adapter is not compatible with Mac or if I need a patch. @syscl do you know of any patch or fix to allow audio through the usb-c to hdmi adapter? It doesn't show up in my audio speaker output in MacOS.

**Comment by R1MnTnA** [comment]
Sorry @riptidewave93 I just realized you have usb-c to display port, not HDMI. Still I think it's worth a shot to try a different adapter after reading those reviews.

**Comment by riptidewave93** [comment]
@R1MnTnA I have no issues trying another adapter, but I can confirm this adapter does work with Linux and Windows without issue. With that said, are there any recommendations on an adapter that's a mini-display port?

**Comment by R1MnTnA** [comment]
This one seems to have all positive reviews from Mac users. - UPTab USB-C Type C to Mini DisplayPort Adapter 4K@60Hz https://www.amazon.com/dp/B01N4FQNYW/ref=cm_sw_r_cp_api_S-KQybB5E1JFV

**Comment by riptidewave93** [comment]
@R1MnTnA I will wait for it to be in stock and then see if that adapter gives me any better luck. With that said, as mentioned earlier the adapter works with Windows and Linux on the XPS 13, so I doubt it's the adapter.

**Comment by aizigao** [comment]
I have 2 extend display which one has hdmi port,I use type c  to hdmi adapter， it works well。

**Comment by syscl** [comment]
Hi @-all, please give new SSDT-XHC a try.

@R1MnTnA @bozma88 @aizigao ...

syscl

**Comment by riptidewave93** [comment]
@syscl Thanks, for me this change has resolved my issue! 👍

**Comment by bozma88** [comment]
@riptidewave93, still no hotpugging, right?

**Comment by riptidewave93** [comment]
@bozma88 Hotplug with my USB-C to Displayport adapter is working fine. If you are asking about Hotplug with USB-C devices, such as my Dell D200 adapter, that still does not hotplug correctly but that should probably be kept to the issue at https://github.com/syscl/XPS9350-macOS/issues/33

**Comment by bozma88** [comment]
Yes, you're right.

**Comment by R1MnTnA** [comment]
@syscl Thank you for this update. Although I will have to wait a few more days to try it on my 9360. Dell is currently replacing my motherboard with the a new version. As soon as I get it back I'll try this and report back. Again thank you for all your hard work and dedication.

**Comment by syscl** [comment]
Hi @riptidewave93 , which issue has been solved with the latest SSDT-XHC?

Thank you,
syscl

**Comment by aizigao** [comment]
@syscl I had tried the last file yesterday,  it works well until now ，great jobs！
---
买了个 type c 转 minidp 还没发货，刚退了 😄

**Comment by syscl** [comment]
@aizigao Which one works? Or with the latest SSDT-XHC solve some issue?

-------
@aizigao 之前不用SSDT-XHC的时候无法正确工作吗？因为我没有设备，只能根据你们的反馈情况来判断？新的SSDT－XHC修复了哪一个问题呢？谢谢

syscl

**Comment by aizigao** [comment]
我刚删了回复，是因为我刚屏又黑了一下。。。现在用的是最新的文件的说。

**Comment by riptidewave93** [comment]
@syscl The original issue in the OP, so my USB-C to DisplayPort adapter is now working with my monitor, and it supports hotplug.

**Comment by syscl** [comment]
Hello @riptidewave93 , could you please provide your ioreg through this [way](https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/)? 

Thank you!
syscl

**Comment by riptidewave93** [comment]
@syscl Attached you can find a dump. Hope I did this correctly. 😄 
[MacBook.zip](https://github.com/syscl/XPS9350-macOS/files/833306/MacBook.zip)

**Comment by syscl** [comment]
@riptidewave93 Thank you, but I do not see any USB-C device...

syscl

**Comment by riptidewave93** [comment]
@syscl if it helps, this is just a thunderbolt 3 to DisplayPort, so it's possible it does not show as a USB device. Maybe that explains why it does not show as a USB-C device?

**Comment by syscl** [comment]
@riptidewave93 Oh, I see...
![snip20170310_7](https://cloud.githubusercontent.com/assets/11594858/23787920/ebedca5c-0539-11e7-85b6-e1473b5f9f7a.png)

So, you use your monitor with USB-C port directly? Without any other adapter/dongle? And the monitor use USB-C port as well?

Thank you,
syscl

**Comment by riptidewave93** [comment]
@sysclI I use a USB-C to Mini DisplayPort adapter, specifically [this one](https://www.amazon.com/AllSmartLife-DisplayPort-Aluminium-resolution-ChromeBook/dp/B017TZTMBG), to directly connect my montior to my laptop.

**Comment by syscl** [comment]
Now, I know this is a DP connector, @riptidewave93 please try this config.plist I made for you

[config.plist.zip](https://github.com/syscl/XPS9350-macOS/files/833370/config.plist.zip)


Then attach the new ioreg. I correct the connector-type

syscl

**Comment by bozma88** [comment]
On XPS line, thunderbolt chip and USB 3.1 chip activate and expose themselves to the OS only when a peripheral is attached. This is why we don't have hotplug for USB and TB, because natively MacOS does not handle this behaviour. But I think that someone (@wmchris) managed to make it work on 9550.

**Comment by riptidewave93** [comment]
@syscl Applied the config directly to the Clover folder in EFI and rebooted. External monitor no longer works, same issue as in OP. Laptop detects the display, but nothing outputs.

[MacBook.zip](https://github.com/syscl/XPS9350-macOS/files/833423/MacBook.zip)

**Comment by syscl** [comment]
So precious config.plist work, but the latest/experimental one break the output, right?

syscl

**Comment by riptidewave93** [comment]
@syscl Correct. 😄

**Comment by syscl** [comment]
Thank you for your feedback. Hmmm, weird, DP should have connector-type <00 04 00 00> but we need to use HDMI connector-type <00 08 00 00> to light the external screen up.

syscl

**Comment by riptidewave93** [comment]
Hmm, so I restored my last config.plist but now my adapter no longer works... will need to spend more time playing with this.

**Comment by riptidewave93** [comment]
@syscl Huh, well now I am stumped. No matter what I do, I can no longer get my display adapter to work. With, or without, the above config.plist you shared. If it would be easier, and you are in the US, feel free to email me and I will pay for an adapter for you.

**Comment by R1MnTnA** [comment]
@riptidewave93 not sure if this would help, but try refreshing your kext cache. 
`sudo touch /System/Library/Extensions && sudo kextcache -u /` and reboot.

**Comment by riptidewave93** [comment]
@R1MnTnA Gave it a try, it has no effect on the issue.

**Comment by syscl** [comment]
@riptidewave93 Please post ioreg with monitor plug in this time.

syscl

**Comment by syscl** [comment]
@riptidewave93 Please try the latest deploy.sh, I've fixed some XHC issue and added a patch for it.

syscl

**Comment by riptidewave93** [comment]
@syscl Gave it a try, still no go. Attached is the ioreg, and a copy of my Clover folder just in case.
[Archive.zip](https://github.com/syscl/XPS9350-macOS/files/836368/Archive.zip)

**Comment by syscl** [comment]
@riptidewave93 Please give this a try 
[CLOVER.zip](https://github.com/syscl/XPS9350-macOS/files/836381/CLOVER.zip)

Note also rebuild kernel cache by typing:

```
sudo kextcache -i /
```
syscl

**Comment by riptidewave93** [comment]
@syscl Gave it try, still no go. Attached is the ioctl with monitor attached.
[Chris’s MacBook Pro - 2.zip](https://github.com/syscl/XPS9350-macOS/files/836383/Chris.s.MacBook.Pro.-.2.zip)

**Comment by syscl** [comment]
@riptidewave93 How about plug in the monitor then reboot?

syscl

**Comment by riptidewave93** [comment]
@syscl Rebooted with monitor plugged in, still not working. Let me know if you want me to try anything else.

**Comment by syscl** [comment]
Thank you for your dedication. I will post it tomorrow morning because I need to have a rest. In USA, 3:00 am now due to the summer time TT

syscl
